[package]
name = "horizon"
version = "0.1.0"
authors = ["Roland Mikhel <roland.mikhel@gmail.com>"]
repository = "https://github.com/Roolli/Horizon/"
edition = "2018"
description="Cross-platform 2D/3D engine using WebGPU and Rust (WebAssembly for browsers)"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[bin]]
name ="horizon-native"
test = false
bench = false
path = "src/main.rs"


#[target.'cfg(target_arch="x86_64")'.dependencies]
#rusty_v8 = "0.15.0"

[features]
default = ["console_error_panic_hook"]


[dependencies]
wasm-bindgen = "0.2.69"

winit = "0.24.0"
imgui-wgpu = "0.12.0"
nalgebra = "0.24.0"
nalgebra-glm="0.10.0"
ncollide3d = "0.27.0"
nphysics3d = "0.19"
ncollide2d = "0.27"
nphysics2d = "0.19"
env_logger = "0.8.2"
futures = "0.3.12"
bytemuck=  { version = "1.5.0", features = ["derive"]}
image = "0.23"
anyhow = "1.0.38"


[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2.0"
glob ="0.3"
shaderc="0.7.0"
rayon="1.5.0"

[dependencies.wgpu]
version = "0.6.2"
features=["vulkan-portability"]
# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
[target.'cfg(target_arch="wasm32")'.dependencies]
wee_alloc = { version = "0.4.5", optional = true }
console_error_panic_hook = { version = "0.1.6", optional = true }



# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.


[dev-dependencies]
wasm-bindgen-test = "0.3.19"


[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
